### ISSUE TITLE
Map is partially loaded and search function doesn't work at first visit until user refresh the page.

### ISSUE THREAD

**Issue by resant18** [gwg-women/gwg-women-techmakers#157] opened 2018-04-02 00:11 UTC
How to reproduce the issue:
1. Open in new incognito window.
2. Wiki info and map will be loaded partially along with blank grey part of map after delay few seconds. Also at this stage, the search place function doesn't work.
3. User need to refresh the page to properly load the page.

**Comment by khusbuchandra** [comment] 2018-04-02 04:25
@resant18 , while you are at it, I would like to share my findings. In the first load geolocation.getCurrentPosition takes alot of time and the reason behind it is being said to be what is discussed here :
https://stackoverflow.com/questions/47581575/only-request-geolocation-information-in-response-to-a-user-gesture
Since the position is not loaded the Map shows grey and once we get position the map re-renders. Now about the places I see that as we are fetching places on OnMapReady but in that event we don't have the position detail for the first load which results in request for places as null. This causes the side bar for places to be empty. 
Once the position from geolocation is loaded the map loads correctly and after a refresh again the OnMapReady gets called which causes the places to load correctly.
As per the link above it's mentioned that Google doesn't recommend getting user location on load. I believe that is the cause for all our concerns. Point me out if I am missing something.
cc: @sgluzins , @sonalikatara

**Comment by resant18** [comment] 2018-04-02 05:01
@khusbuchandra That's exactly what I found and I would like to discuss on how to solve it. As we want user to have good experience by sending response as soon as we can put in the display, I was thinking to give initial lat & lang before loading the map. After I give a temporary coordinate, in few seconds later the map is loaded properly, as well as the place list, since as you said it doesn't have coordinate initially. Whether giving initial coordinate or changing the process by providing button for user to request their location or else, I'm open to any suggestion. @sgluzins, @sonalikatara

**Comment by khusbuchandra** [comment] 2018-04-02 05:24
Thanks @resant18, You are correct about the options we have to resolve it. 

1. Have the initial lat/lng as Google headquater location or some location hard-coded for initial load. This would solve the problem with Map and places. Only problem is that in initial load for few seconds it will display details for the incorrect location and would auto-correct to the user's location. Will that be a better experience than not having things loaded or incorrect details for few seconds won't be favorable for the app?

2. As Google recommends, we add some controls on initial load asking user if they would like to search and request their location. This would be a shift from what we had planned till now of directly getting the map and results as soon as the user opens the application.

Need to find if there are any better solutions for it and would appreciate suggestions from the team @gwg-women/all-gwg-women

**Comment by sgluzins** [comment] 2018-04-02 05:43
Hi! Yes, I also agree! I found the same information a while back and when first implementing the built-in service vs calling the API endpoint, I had it load San Francisco on initial load and then reset to the user's coordinates because I read that about initial load. We ended up removing that a while back though - we had a lot of moving parts at once so I figured we just didn't want it and it was resolved another way. I'd be good if we added something similar back in - maybe we can add text somewhere on the page or in the header that says "Please wait while we find your location" or something along those lines so the user understands that we don't think they're in SF or whatever location we choose for initial load.

I'm good with the option of loading a different location first but trying to think of some alternatives: 
- add in some loading spinners? so a user only sees the correct details once it shows their location

**Comment by khusbuchandra** [comment] 2018-04-03 01:11
loading spinner seems a good option @sgluzins . 
I also did some changes PR #161 for the places to load after user's location is determined in the initial load. I am not getting the issue now after deleting the cache related to places not loading. But would need fresh set of eyes to validate.

**Comment by sgluzins** [comment] 2018-04-03 04:49
oh great!! so I just checked out the branch - I am still having issues with incognito on the first load. Were you able to get it working on your end for that as well? I didn't seem to see any issues when I wasn't in incognito though.

**Comment by khusbuchandra** [comment] 2018-04-03 05:04
@sgluzins , I was working on the search box and its integration with places, I believe only the issue related to places not loading in first load would be resolved. By resolved I mean after some time on first load places will be loaded not immediately. But the issues with map remains the same, we need to go for some loading spinner or splash screen. Something to keep the user engaged while the map gets loaded.

**Comment by sgluzins** [comment] 2018-04-03 05:38
@khusbuchandra perfect! we are on the same page and I was seeing the same behavior. I'll go ahead and open a new issue and work on that piece (loading spinner/splash screen) unless you have already started.

**Comment by khusbuchandra** [comment] 2018-04-03 05:45
I haven't started on it, would need to know from @resant18  as well as she started on this investigation. As well as @sonalikatara was onto something with the maps, want to make sure we all are on the same page. Or we can maybe take up the conversation on slack?

**Comment by sonalikatara** [comment] 2018-04-03 16:56
I agree that we need to have a loading spinner when the app is loading the first time. It is better than setting a default location and there is no way around this delay, we have to wait for the first time for geolocation, after that we are storing the pos in local cache and have a static map too.

I am looking into the partially loaded map.

**Comment by resant18** [comment] 2018-04-04 02:11
I initiated the location with lat & lng 0, 0 and did testing with slow network, it seems works perfectly. I don't even see the location 0, 0, and the map is loaded with my current position right away. I will made the PR tonight and will let you all know after.

**Comment by khusbuchandra** [comment] 2018-04-06 02:52
I am closing this issue for now.

**Closed as completed by khusbuchandra** 2018-04-06 02:52 UTC
Labels: bug, in progress
